import { cssFontStack, ms, px } from './format';
import {
  breakpoint,
  color,
  containerMax,
  fontFamily,
  fontSize,
  fontWeight,
  motion,
  radius,
  shadow,
  size,
  spacing,
} from './tokens';

/** Framework-free `:root` custom properties (`--suskii-*`) for code outside Tailwind. */
export function getCssVariables(): string {
  const vars: [string, string][] = [
    ...Object.entries(color).map(([k, v]): [string, string] => [`color-${k}`, v]),
    ...Object.entries(fontFamily.web).map(([k, v]): [string, string] => [
      `font-${k}`,
      cssFontStack(v),
    ]),
    ...Object.entries(fontWeight).map(([k, v]): [string, string] => [
      `font-weight-${k}`,
      String(v),
    ]),
    ...Object.entries(fontSize).flatMap(([k, { size, lineHeight }]): [string, string][] => [
      [`font-size-${k}`, px(size)],
      [`line-height-${k}`, String(lineHeight)],
    ]),
    ...Object.entries(spacing).map(([k, v]): [string, string] => [`space-${k}`, px(v)]),
    ...Object.entries(radius).map(([k, v]): [string, string] => [`radius-${k}`, px(v)]),
    ...Object.entries(shadow).map(([k, v]): [string, string] => [`shadow-${k}`, v]),
    ...Object.entries(breakpoint).map(([k, v]): [string, string] => [`breakpoint-${k}`, px(v)]),
    ['container-max', px(containerMax)],
    ...Object.entries(size).map(([k, v]): [string, string] => [`size-${k}`, px(v)]),
    ...Object.entries(motion.duration).map(([k, v]): [string, string] => [`duration-${k}`, ms(v)]),
    ...Object.entries(motion.easing).map(([k, v]): [string, string] => [`easing-${k}`, v]),
  ];
  return [
    '/* Generated by @suskii/design-tokens. Do not edit; change src/tokens.ts instead. */',
    ':root {',
    ...vars.map(([name, value]) => `  --suskii-${name}: ${value};`),
    '}',
    '',
  ].join('\n');
}
