// Side effect first: configures Zod before any schema below is constructed.
import './zod-setup';

export { BRAND, NEWSLETTER_CONSENT_VERSION } from './brand';
export {
  DEFAULT_CURRENCY,
  SUPPORTED_CURRENCIES,
  currencyCodeSchema,
  isSupportedCurrency,
  type CurrencyCode,
} from './currency';
export {
  DEFAULT_LOCALE,
  SUPPORTED_LOCALES,
  isSupportedLocale,
  localeCodeSchema,
  type LocaleCode,
} from './locale';
export { VERTICALS, isVertical, verticalSchema, type Vertical } from './vertical';
export {
  DEFAULT_TRAVELLERS,
  MAX_TRAVELLERS,
  MIN_ADULTS,
  TRAVELLER_AGE_BANDS,
  TRAVELLER_ISSUES,
  TRAVELLER_TYPES,
  canDecrement,
  canIncrement,
  stepTravellers,
  totalTravellers,
  travellerCountsSchema,
  type TravellerCounts,
  type TravellerType,
} from './travellers';
export {
  PERMISSIONS,
  ROLES,
  ROLE_PERMISSIONS,
  STAFF_ROLES,
  hasPermissions,
  isRole,
  isStaff,
  permissionsFor,
  type Permission,
  type Role,
} from './rbac';
export {
  PASSWORD_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  authTransportSchema,
  displayNameSchema,
  emailSchema,
  loginRequestSchema,
  otpCodeSchema,
  passwordSchema,
  phoneSchema,
  registerRequestSchema,
  type AuthTransport,
  type LoginRequest,
  type RegisterRequest,
} from './auth';
export {
  ROUNDING_MODES,
  add,
  allocate,
  assertCurrency,
  compare,
  convert,
  crossRate,
  currencyExponent,
  equals,
  formatMoney,
  formatRate,
  fromWire,
  identityRate,
  invertRate,
  isNegative,
  isZero,
  maxOf,
  minOf,
  money,
  multiply,
  multiplyRatio,
  negate,
  parseMoney,
  parseRate,
  percentageOf,
  roundDiv,
  subtract,
  sum,
  toDecimalString,
  toWire,
  zero,
  type ExchangeRate,
  type Money,
  type MoneyWire,
  type RoundingMode,
} from './money';
export { moneyWireSchema } from './money-schema';
export {
  EARLIEST_TIME_ZONE,
  addDays,
  daysBetween,
  earliestToday,
  isValidDate,
  isValidTimeZone,
  localDate,
  localToUtc,
  utcOffsetMinutes,
  utcToLocal,
} from './time';
export {
  CABIN_CLASSES,
  MAX_ADULTS_PER_ROOM,
  MAX_ADVANCE_DAYS,
  MAX_CHILDREN_PER_ROOM,
  MAX_CHILD_AGE,
  MAX_FLIGHT_SLICES,
  MAX_HOTEL_ROOMS,
  MAX_STAY_NIGHTS,
  MIN_MULTI_CITY_LEGS,
  SEARCH_ISSUES,
  TRIP_TYPES,
  cabinClassSchema,
  createFlightSearchFormSchema,
  createFlightSearchRequestSchema,
  createHotelSearchRequestSchema,
  flightSearchFormSchema,
  flightSearchRequestSchema,
  hotelDestinationSchema,
  hotelRoomSchema,
  hotelSearchRequestSchema,
  iataCodeSchema,
  isoDateSchema,
  toFlightSearchRequest,
  type CabinClass,
  type FlightSearchForm,
  type FlightSearchRequest,
  type FlightSearchRequestInput,
  type HotelSearchRequest,
  type HotelSearchRequestInput,
  type SearchSchemaOptions,
  type TripType,
} from './search';
export {
  QueryBuilder,
  emptyFlightDraft,
  emptyHotelDraft,
  flightDraftToInput,
  flightFormToDraft,
  flightFormToParams,
  hotelDraftToInput,
  hotelFormToParams,
  parseFlightSearchParams,
  parseHotelSearchParams,
  type FlightFormDraft,
  type FlightLegDraft,
  type HotelFormDraft,
  type HotelRoomDraft,
  type ParsedSearch,
  type QueryInput,
} from './search-url';
export {
  ADDON_TYPES,
  VERTICAL_FORM_ISSUES,
  VISA_PURPOSES,
  addonsDraftToInput,
  addonsFormSchema,
  addonsFormToParams,
  bookingReferenceSchema,
  createAddonsFormSchema,
  createPackagesFormSchema,
  createToursFormSchema,
  createVisaFormSchema,
  emptyAddonsDraft,
  emptyPackagesDraft,
  emptyToursDraft,
  emptyVisaDraft,
  lastNameSchema,
  packagesDraftToInput,
  packagesFormSchema,
  packagesFormToParams,
  parseAddonsParams,
  parsePackagesParams,
  parseToursParams,
  parseVisaParams,
  toursFormSchema,
  toursFormToParams,
  visaFormSchema,
  visaFormToParams,
  type AddonType,
  type AddonsForm,
  type AddonsFormDraft,
  type PackagesForm,
  type PackagesFormDraft,
  type ToursForm,
  type ToursFormDraft,
  type VisaForm,
  type VisaFormDraft,
  type VisaPurpose,
} from './vertical-forms';
