/**
 * The Zod-free subset of @suskii/shared: constants and pure helpers. Browser code that runs before
 * any validation (form rendering, formatting) imports `@suskii/shared/lite`, so Zod stays out of
 * the web homepage's initial JavaScript; the main entry, with the schemas, loads where it is
 * needed (for example when a form is submitted). lite.test.ts keeps this entry free of Zod.
 */
export { BRAND, NEWSLETTER_CONSENT_VERSION } from './brand';
export {
  DEFAULT_CURRENCY,
  SUPPORTED_CURRENCIES,
  isSupportedCurrency,
  type CurrencyCode,
} from './currency-codes';
export {
  DEFAULT_LOCALE,
  SUPPORTED_LOCALES,
  isSupportedLocale,
  type LocaleCode,
} from './locale-codes';
export {
  ROUNDING_MODES,
  add,
  currencyExponent,
  formatMoney,
  fromWire,
  money,
  roundDiv,
  toWire,
  type Money,
  type MoneyWire,
  type RoundingMode,
} from './money';
export {
  CABIN_CLASSES,
  MAX_FLIGHT_SLICES,
  MIN_MULTI_CITY_LEGS,
  TRIP_TYPES,
  type CabinClass,
  type TripType,
} from './search-limits';
export { addDays, earliestToday, isValidDate } from './time';
export {
  DEFAULT_TRAVELLERS,
  MAX_TRAVELLERS,
  TRAVELLER_TYPES,
  canDecrement,
  canIncrement,
  stepTravellers,
  totalTravellers,
  type TravellerCounts,
  type TravellerType,
} from './traveller-rules';
export {
  BOOKING_IN_PROGRESS_STATUSES,
  BOOKING_STATUSES,
  BOOKING_TERMS_VERSION,
  type BookingStatus,
} from './booking-rules';
export {
  FULL_NAME_MAX_LENGTH,
  GENDERS,
  NAME_MAX_LENGTH,
  PASSENGER_ISSUES,
  PASSENGER_TITLES,
  PASSENGER_TYPES,
  ageOn,
  checkPassengers,
  passengerTypeForAge,
  transliterateName,
  type Gender,
  type ItineraryFacts,
  type PassengerIssue,
  type PassengerTitle,
  type PassengerType,
} from './passenger-rules';
export {
  PAYMENT_PLAN_KINDS,
  PAYMENT_PROVIDER_NAMES,
  REFUND_DESTINATIONS,
  REFUND_REASONS,
  REFUND_STATUSES,
  type PaymentPlanKind,
  type PaymentProviderName,
  type RefundDestination,
  type RefundReason,
  type RefundStatus,
} from './payment-plans';
export {
  emptyPassenger,
  FLIGHT_NUMBER_PATTERN,
  flightFacts,
  inhouseFacts,
  normalisePassport,
  normalisePhone,
  passengerDrafts,
  validateCheckout,
  type CheckoutDraft,
  type CheckoutIssue,
  type CheckoutRules,
  type FieldIssues,
  type FlightFactsInput,
  type GuestDraft,
  type InhouseFactsInput,
  type PassengerDraft,
} from './checkout-draft';
export {
  ADDON_DETAIL_FIELDS,
  ADDON_PRICING_BASES,
  ADDON_PRODUCT_TYPES,
  CATALOG_STATUSES,
  CLOSED_VISA_STATUSES,
  DEPARTURE_STATUSES,
  MAX_ADDON_DAYS,
  MAX_CANCELLATION_TIERS,
  PER_PERSON_ISSUES,
  VISA_APPLICATION_STATUSES,
  VISA_DOCUMENT_EXTENSIONS,
  VISA_DOCUMENT_STATUSES,
  VISA_DOCUMENT_TYPES,
  VISA_OFFICER_TRANSITIONS,
  VISA_REQUIREMENTS,
  VISA_UPLOAD_STATUSES,
  VOUCHER_ALPHABET,
  VOUCHER_CODE_LENGTH,
  VOUCHER_QR_PREFIX,
  addonUnits,
  cancellationRefund,
  coveredDays,
  formatVoucherCode,
  parseVoucherCode,
  perPersonTotal,
  refundBpsFor,
  safeFileName,
  seatsFor,
  sniffDocumentType,
  sortTiers,
  type AddonDetailField,
  type AddonPricingBasis,
  type AddonProductType,
  type CancellationTier,
  type CatalogStatus,
  type DepartureStatus,
  type PerPersonIssue,
  type PerPersonPrices,
  type VisaApplicationStatus,
  type VisaDocumentStatus,
  type VisaDocumentType,
  type VisaRequirement,
} from './inhouse';
export {
  MAX_PRICE_ALERTS,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_CHANNELS,
  NO_PRIME_BENEFITS,
  PRIME_PERIODS,
  REFERRAL_CODE_LENGTH,
  REFERRAL_STATUSES,
  alertEndsOn,
  defaultPreference,
  isMandatoryChannel,
  memberMarkupSaving,
  parseReferralCode,
  primeTermEnd,
  resolvePreferences,
  shouldNotifyPrice,
  type NotificationCategory,
  type NotificationChannel,
  type NotificationMatrix,
  type PrimeBenefits,
  type PrimePeriod,
  type ReferralStatus,
} from './accounts';
