/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public keys that verify access tokens (RFC 7517) */
        get: operations["getJwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (Postgres and Redis reachable) */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Browse the immutable audit log (newest first) */
        get: operations["adminListAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user */
        get: operations["adminGetUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a user's roles
         * @description Audited. Signs the user out everywhere so the new roles apply immediately.
         */
        put: operations["adminSetUserRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with an Apple identity token */
        post: operations["signInWithApple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm an email address with the emailed token */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with a Google ID token */
        post: operations["signInWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in with email and password
         * @description Returns a session, or an MFA challenge when the account has MFA enabled.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign out this session
         * @description Revokes the session identified by the access token, the refresh token in the body, or the refresh cookie (with X-CSRF-Token). Always succeeds.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a sign-in with a TOTP or recovery code */
        post: operations["verifyMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Text a 6-digit sign-in code to a phone number
         * @description Codes expire after 5 minutes; a new code can be requested every 60 seconds.
         */
        post: operations["requestSignInOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in (or sign up) with a phone code */
        post: operations["verifySignInOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password reset link
         * @description Always answers 202, whether or not the email is registered.
         */
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with the emailed token
         * @description Signs the account out on every device.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and get a new access token
         * @description Every refresh token works once. Presenting a used token again revokes the whole session (theft detection). Cookie transport also requires X-CSRF-Token.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account with email and password
         * @description Always answers 202 so the response never reveals whether the email is registered. New accounts get a verification email; existing ones get a notice. Sign in afterwards.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile details */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/v1/me/email/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send the email verification link again */
        post: operations["resendEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/mfa/recovery-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replace all recovery codes */
        post: operations["regenerateRecoveryCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/mfa/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start authenticator-app enrolment */
        post: operations["startTotpEnrolment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/mfa/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm enrolment with a code and receive recovery codes
         * @description Marks the current session as MFA-verified; refresh the session to receive an access token that carries it.
         */
        post: operations["confirmTotpEnrolment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/mfa/totp/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Turn off MFA (not allowed for staff) */
        post: operations["disableTotp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the password
         * @description Signs out every other session.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Text a code to add or change the phone number */
        post: operations["requestPhoneVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/phone/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm the phone number with the texted code */
        post: operations["verifyPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signed-in devices */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign out a device */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/sessions/revoke-others": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign out every other device */
        post: operations["revokeOtherSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Accepted: {
            /** @constant */
            status: "accepted";
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            email: string | null;
            phone: string | null;
            displayName: string | null;
            /** @enum {string} */
            status: "active" | "disabled";
            roles: ("customer" | "super_admin" | "operations" | "finance" | "support" | "content_manager" | "visa_officer")[];
            mfaEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        AuditLogEntry: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            /** @enum {string} */
            actorType: "user" | "system" | "anonymous";
            actorUserId: string | null;
            action: string;
            targetType: string | null;
            targetId: string | null;
            requestId: string | null;
            metadata: {
                [key: string]: unknown;
            };
        };
        AuditLogPage: {
            items: components["schemas"]["AuditLogEntry"][];
            nextCursor: string | null;
        };
        AuthSession: {
            /** @constant */
            status: "authenticated";
            user: components["schemas"]["AuthUser"];
            /** Format: uuid */
            sessionId: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            /** Format: date-time */
            refreshTokenExpiresAt: string;
            accessToken?: string;
            refreshToken?: string;
            csrfToken?: string;
        };
        AuthUser: {
            /** Format: uuid */
            id: string;
            email: string | null;
            emailVerified: boolean;
            phone: string | null;
            phoneVerified: boolean;
            displayName: string | null;
            roles: ("customer" | "super_admin" | "operations" | "finance" | "support" | "content_manager" | "visa_officer")[];
            mfaEnabled: boolean;
            hasPassword: boolean;
        };
        ChangePasswordRequestInput: {
            currentPassword: string;
            newPassword: string;
        };
        ForgotPasswordRequestInput: {
            email: string;
        };
        HealthStatus: {
            /** @constant */
            status: "ok";
        };
        Jwks: {
            keys: ({
                kty: string;
                kid: string;
                alg: string;
                /** @constant */
                use: "sig";
                crv?: string;
                x?: string;
            } & {
                [key: string]: unknown;
            })[];
        };
        LoginRequestInput: {
            email: string;
            password: string;
            /**
             * @default token
             * @enum {string}
             */
            transport: "cookie" | "token";
        };
        LogoutRequestInput: {
            refreshToken?: string;
        };
        MfaChallenge: {
            /** @constant */
            status: "mfa_required";
            mfaToken: string;
            /** Format: date-time */
            expiresAt: string;
            methods: ("totp" | "recovery_code")[];
        };
        MfaCodeRequestInput: {
            code?: string;
            recoveryCode?: string;
        };
        MfaVerifyRequestInput: {
            mfaToken: string;
            code?: string;
            recoveryCode?: string;
            /**
             * @default token
             * @enum {string}
             */
            transport: "cookie" | "token";
        };
        OtpDispatched: {
            /** @constant */
            status: "accepted";
            expiresInSeconds: number;
            resendAfterSeconds: number;
        };
        OtpRequestInput: {
            phone: string;
        };
        OtpVerifyRequestInput: {
            phone: string;
            code: string;
            /**
             * @default token
             * @enum {string}
             */
            transport: "cookie" | "token";
        };
        PhoneRequestInput: {
            phone: string;
        };
        PhoneVerifyRequestInput: {
            phone: string;
            code: string;
        };
        /** @description RFC 9457 problem details (application/problem+json). */
        ProblemDetails: {
            /** @description Problem type URN, e.g. urn:suskii:problem:validation-failed */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @description Quote this when contacting support. */
            requestId?: string;
            /** @description Field-level validation issues (validation-failed only). */
            errors?: {
                /** @enum {string} */
                location: "body" | "query" | "params";
                path: string;
                code: string;
                message: string;
            }[];
        };
        ReadinessStatus: {
            /** @enum {string} */
            status: "ok" | "unavailable";
            checks: {
                /** @enum {string} */
                database: "up" | "down";
                /** @enum {string} */
                redis: "up" | "down";
            };
        };
        RecoveryCodes: {
            recoveryCodes: string[];
        };
        RefreshRequestInput: {
            refreshToken?: string;
        };
        RegisterRequestInput: {
            email: string;
            password: string;
            displayName?: string;
        };
        ResetPasswordRequestInput: {
            token: string;
            password: string;
        };
        SessionList: {
            sessions: components["schemas"]["SessionSummary"][];
        };
        SessionSummary: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            authMethod: "password" | "otp" | "google" | "apple";
            userAgent: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            mfaVerified: boolean;
            current: boolean;
        };
        SetRolesRequestInput: {
            roles: ("customer" | "super_admin" | "operations" | "finance" | "support" | "content_manager" | "visa_officer")[];
        };
        SignInResult: components["schemas"]["AuthSession"] | components["schemas"]["MfaChallenge"];
        SocialSignInRequestInput: {
            idToken: string;
            nonce?: string;
            displayName?: string;
            /**
             * @default token
             * @enum {string}
             */
            transport: "cookie" | "token";
        };
        TotpConfirmRequestInput: {
            code: string;
        };
        TotpSetup: {
            secret: string;
            otpauthUri: string;
        };
        UpdateProfileRequestInput: {
            displayName: string;
        };
        VerificationTokenRequestInput: {
            token: string;
        };
    };
    responses: {
        /** @description Validation failed */
        Problem400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Authentication required */
        Problem401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Forbidden */
        Problem403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Not found */
        Problem404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Conflict */
        Problem409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Unprocessable content */
        Problem422: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Too many requests */
        Problem429: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Internal server error */
        Problem500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Service unavailable */
        Problem503: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getJwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jwks"];
                };
            };
            400: components["responses"]["Problem400"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            400: components["responses"]["Problem400"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            400: components["responses"]["Problem400"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
            /** @description Service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
        };
    };
    adminListAuditLogs: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                action?: string;
                actorUserId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    adminGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    adminSetUserRoles: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRolesRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            404: components["responses"]["Problem404"];
            409: components["responses"]["Problem409"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    signInWithApple: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialSignInRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResult"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            404: components["responses"]["Problem404"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationTokenRequestInput"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem400"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    signInWithGoogle: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialSignInRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResult"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            404: components["responses"]["Problem404"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResult"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequestInput"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem400"];
            403: components["responses"]["Problem403"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    verifyMfa: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    requestSignInOtp: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequestInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpDispatched"];
                };
            };
            400: components["responses"]["Problem400"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    verifySignInOtp: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignInResult"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequestInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            400: components["responses"]["Problem400"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequestInput"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem400"];
            422: components["responses"]["Problem422"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequestInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            400: components["responses"]["Problem400"];
            422: components["responses"]["Problem422"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    resendEmailVerification: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    regenerateRecoveryCodes: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodes"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    startTotpEnrolment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TotpSetup"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            409: components["responses"]["Problem409"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    confirmTotpEnrolment: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TotpConfirmRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodes"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            409: components["responses"]["Problem409"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    disableTotp: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaCodeRequestInput"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            403: components["responses"]["Problem403"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequestInput"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            409: components["responses"]["Problem409"];
            422: components["responses"]["Problem422"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    requestPhoneVerification: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneRequestInput"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpDispatched"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    verifyPhone: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhoneVerifyRequestInput"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUser"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            409: components["responses"]["Problem409"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            404: components["responses"]["Problem404"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
    revokeOtherSessions: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when the request is authenticated with session cookies: echo the csrf cookie value. */
                "X-CSRF-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem400"];
            401: components["responses"]["Problem401"];
            429: components["responses"]["Problem429"];
            500: components["responses"]["Problem500"];
        };
    };
}
