/**
 * Builds src/crypto/common-passwords.ts, the bundled list of the most used passwords that meet the
 * length policy (ASVS 5.0 V6.2.4: at least the top 3000). Source: the NCSC "100k most used
 * passwords" list (derived from Have I Been Pwned breach data), as published in SecLists
 * (Passwords/Common-Credentials/100k-most-used-passwords-NCSC.txt, MIT licence). Run when
 * refreshing the list, then review the diff:
 *
 *   pnpm --filter @suskii/api passwords:build <path to the NCSC list>
 */
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { PASSWORD_MAX_LENGTH, PASSWORD_MIN_LENGTH } from '@suskii/shared';

const OUT_FILE = join(__dirname, '..', 'src', 'crypto', 'common-passwords.ts');

async function main(): Promise<void> {
  const source = process.argv[2];
  if (!source) throw new Error('Pass the path to 100k-most-used-passwords-NCSC.txt');
  const lines = (await readFile(source, 'utf8')).split(/\r?\n/);
  const seen = new Set<string>();
  const kept: string[] = [];
  for (const line of lines) {
    const candidate = line.trim().toLowerCase();
    if (candidate.length < PASSWORD_MIN_LENGTH || candidate.length > PASSWORD_MAX_LENGTH) continue;
    // Keep the template literal below plain text.
    if (/[`\\]|\$\{/.test(candidate) || seen.has(candidate)) continue;
    seen.add(candidate);
    kept.push(candidate);
  }
  const body = [
    '/**',
    ' * Generated by scripts/build-common-passwords.ts; do not edit by hand.',
    ` * The ${kept.length} most used passwords of ${PASSWORD_MIN_LENGTH} to ${PASSWORD_MAX_LENGTH} characters, lower case,`,
    ' * in order of use. Source: NCSC 100k most used passwords (from Have I Been Pwned), via',
    ' * SecLists (https://github.com/danielmiessler/SecLists), MIT licence, (c) 2018 Daniel Miessler.',
    ' */',
    `export const COMMON_PASSWORDS_TEXT = \`${kept.join('\n')}\`;`,
    '',
  ].join('\n');
  await writeFile(OUT_FILE, body);
  process.stdout.write(`wrote ${kept.length} passwords to ${OUT_FILE}\n`);
}

void main();
